export const ACTIONS = {
  SEND_REGISTRATION: 'SEND_REGISTRATION',
  SEND_REGISTRATION_CONFIRM: 'SEND_REGISTRATION_CONFIRM',
  SEND_LOGIN: 'SEND_LOGIN',
  LOG_OUT: 'LOG_OUT',
  BOOTSTRAP_SAGA: 'BOOTSTRAP_SAGA',
  SEND_POST: 'SEND_POST',
  GET_MY_POSTS: 'GET_MY_POSTS',
};
